"""update_meteo_data_table

Revision ID: 81c1a7292e7e
Revises: 1a40c4dc218d
Create Date: 2026-03-26 01:56:24.887142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c1a7292e7e'
down_revision: Union[str, Sequence[str], None] = '1a40c4dc218d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteo_data', 'temperature', new_column_name='temperature_2m', existing_type=sa.Float())
    op.alter_column('meteo_data', 'wind_speed', new_column_name='wind_speed_10m', existing_type=sa.Float())
    op.alter_column('meteo_data', 'humidity', new_column_name='relative_humidity_2m', existing_type=sa.Float())
    op.add_column('meteo_data', sa.Column('getting_timestamp', sa.DateTime(), nullable=True))
    op.add_column('meteo_data', sa.Column('wind_gusts_10m', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('dew_point_1m', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('shortwave_radiation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteo_data', 'temperature_2m', new_column_name='temperature', existing_type=sa.Float())
    op.alter_column('meteo_data', 'wind_speed_10m', new_column_name='wind_speed', existing_type=sa.Float())
    op.alter_column('meteo_data', 'relative_humidity_2m', new_column_name='humidity', existing_type=sa.Float())
    op.drop_column('meteo_data', 'shortwave_radiation')
    op.drop_column('meteo_data', 'dew_point_1m')
    op.drop_column('meteo_data', 'wind_gusts_10m')
    op.drop_column('meteo_data', 'getting_timestamp')
    # ### end Alembic commands ###
